name: ClockIn

on:
  push:
    branches:
      - master
  watch:
    types: [started]
  schedule:
    - cron: '0 */12 * * *'
  workflow_dispatch:

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    if: github.event_name != 'watch' || github.event.repository.owner.id == github.event.sender.id
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          npm install --no-save puppeteer-core chrome-launcher
          sudo apt-get update -y
          sudo apt-get install -y tesseract-ocr
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets.ACCOUNT }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: node clock-in.js
